name: bangladesh

screenshots:
  - description: The 'Bangladesh' Flutter plugin is a powerful tool for displaying a customizable map of Bangladesh..
    path: example/images/Top.jpg
  - description: Image 2 of Bangladesh
    path: example/images/Ep.png
  - description: Image 3 of Bangladesh
    path: example/images/bangladesh-monzim.png
  - description: Image 4 of Bangladesh
    path: example/images/bangladesh-monzim-dark.png

description: The 'Bangladesh' Flutter plugin is a powerful tool for displaying a customizable map of Bangladesh. With division borders highlighted and custom touch feedback, it can be used in a multitude of applications for an engaging user experience.

homepage: https://github.com/Monzim/flutter_bangladesh

version: 0.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
